name: Weekly Stock Forecast

on:
  schedule:
    - cron: '0 1 * * 0'  # ทุกวันอาทิตย์ 08:00 เวลาไทย (UTC+7 = 01:00 UTC)
  workflow_dispatch:

jobs:
  forecast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Forecast
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python forecast.py
